apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: cattle-csp-system
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - env:
        # NOTE: remove this in favor of discovery from setting
        - name: RANCHER_HOSTNAME
          value: {{ .Values.rancherHostname }}
        - name: CATTLE_DEBUG
          value: {{ .Values.debug | quote }}
        image: '{{ template "system_default_registry" . }}{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        name: {{ .Chart.Name }}
        imagePullPolicy: "{{ .Values.image.imagePullPolicy }}"
        ports:
        - name: https
          containerPort: 9443
      serviceAccountName: {{ .Chart.Name }}
